### PR TITLE
Add flag to use alt. boot images to suppress prompt at boot

### PR DESCRIPTION
**Pull request by riverar**
Useful for automation cases.

### CODE REVIEW

**Comment by riverar** [comment]
@gus33000 Do you need me to rev the version numbers? Is this implementation okay or would you prefer something else?

**Comment by gus33000** [comment]
Not too sure about this i'll be honest, I think it's probably doable to change the parameters used here instead given, i think, uefi does make use of eltorito still for this?

https://github.com/gus33000/UUPMediaCreator/blob/master/src/MediaCreationLib.NET/CDImage/CDImageWrapper.cs#L46-L47

There's a few problems that exist before this PR with booting ISOs in ARM64 Hyper-V (complains about certificate used to sign not present in DB).
image

Disabling SecureBoot fixes it, but abnormal

**Comment by riverar** [comment]
Both alternate blobs are signed so that looks like an unrelated error? Or maybe arm64 is busted hmm.

**Comment by riverar** [comment]
Happy to consider alternatives here as long as I get the same result.

**Comment by riverar** [comment]
We can instead change the argument passed into mkisofs/cdimage.exe, agreed.

**Comment by gus33000** [comment]
Thanks!

**Pull request merged**
